### ISSUE TITLE
Request timeout / "No route to host"

### ISSUE THREAD

**Issue by bpurinton** [friedrichknuth/geodata#5]
I am trying to run this CLI on Pleiades (but having the same issue on a local laptop install on Mac OSX).

My command:

```
download_3DEP_DSM --collection 3dep-lidar-dsm \
     --bbox '-157.0846 71.209 -156.133 71.449' \
     --time-range 2017-12-01/2021-12-31 \
      --output-folder .
```

The timeout message:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/bin/download_3DEP_DSM", line 33, in <module>
    sys.exit(load_entry_point('geodata', 'console_scripts', 'download_3DEP_DSM')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/src/geodata/geodata/cli/download_3DEP_DSM.py", line 51, in main
    Planetary.download_3DEP_DSM()
  File "/home4/bpurint1/src/geodata/geodata/dems.py", line 52, in download_3DEP_DSM
    Planetary.request_items(self)
  File "/home4/bpurint1/src/geodata/geodata/dems.py", line 33, in request_items
    catalog = Client.open(self.base_url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/pystac_client/client.py", line 166, in open
    client: Client = cls.from_file(
                     ^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/pystac_client/client.py", line 222, in from_file
    client: Client = super().from_file(href, stac_io)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/pystac/catalog.py", line 1253, in from_file
    result = super().from_file(href, stac_io)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/pystac/stac_object.py", line 630, in from_file
    d = stac_io.read_json(href)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/pystac/stac_io.py", line 205, in read_json
    txt = self.read_text(source, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/pystac_client/stac_api_io.py", line 167, in read_text
    return self.request(href, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home4/bpurint1/sw/miniconda3/envs/ben_py3/lib/python3.11/site-packages/pystac_client/stac_api_io.py", line 214, in request
    raise APIError(str(err))
pystac_client.exceptions.APIError: HTTPSConnectionPool(host='planetarycomputer.microsoft.com', port=443): Max retries exceeded with url: /api/stac/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f01291156d0>: Failed to establish a new connection: [Errno 113] No route to host'))
```

**Comment by friedrichknuth** [comment]
Hmm I'm not sure what is causing this issue for you. 

I just did a clean install on one of our Ubuntu boxes and your command runs fine.

```
download_3DEP_DSM --collection 3dep-lidar-dsm \
     --bbox '-157.0846 71.209 -156.133 71.449' \
     --time-range 2017-12-01/2021-12-31 \
      --output-folder .
```
Returns
```
bounding box: [-157.0846, 71.209, -156.133, 71.449]
time range: 2017-12-01/2021-12-31
15 items found at https://planetarycomputer.microsoft.com/api/stac/v1

downloading:
AK_NorthSlope_B7_2018-dsm-2m-5-11.tif
AK_NorthSlope_B7_2018-dsm-2m-5-10.tif
AK_NorthSlope_B7_2018-dsm-2m-4-12.tif
AK_NorthSlope_B7_2018-dsm-2m-4-11.tif
AK_NorthSlope_B7_2018-dsm-2m-4-10.tif
AK_NorthSlope_B7_2018-dsm-2m-3-11.tif
AK_NorthSlope_B7_2018-dsm-2m-3-10.tif
AK_NorthSlope_B7_2018-dsm-2m-2-11.tif
AK_NorthSlope_B7_2018-dsm-2m-2-10.tif
AK_NorthSlope_B3_2018-dsm-2m-4-12.tif
AK_NorthSlope_B3_2018-dsm-2m-3-12.tif
AK_NorthSlope_B3_2018-dsm-2m-3-11.tif
AK_NorthSlope_B3_2018-dsm-2m-3-10.tif
AK_NorthSlope_B3_2018-dsm-2m-2-11.tif
AK_NorthSlope_B3_2018-dsm-2m-2-10.tif
```

**Comment by bpurinton** [comment]
Oops. A reserved node on Pleiades is apparently not connected to the internet, which is why I get a "no route" error. Closing this, as everything is working perfectly fine now.
